#!/usr/bin/env bash
#transfers a file from our client to a server
if [[ $1 && $2 && $3 && $4 ]]
then
sudo scp -i "$4" "$1" "$3@$2":~/
else
echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
