#!/usr/bin/env bash
# configure the load balancer

sudo apt-get -y update
sudo apt-get -y install haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original
sudo sed -i "\$ a\listen appname\n\tbind 0.0.0.0:80\n\tmode http\n\tstats enable\n\tbalance roundrobin\n\toption httpclose\n\toption forwardfor\n\tserver 929-web-01 35.190.174.178:80 check\n\tserver 929-web-02 35.227.18.143:80 check" /etc/haproxy/haproxy.cfg
sudo service haproxy start
