#!/usr/bin/env bash
#process and pid file
touch /var/run/holbertonscript.pid
echo $$ > /var/run/holbertonscript.pid
trap "echo I hate the kill command" SIGTERM
trap "rm /var/run/holbertonscript.pid" SIGTERM
trap "echo Y U no love me?!" SIGINT
trap "rm /var/run/holbertonscript.pid" SIGQUIT
while ((1))
do
    echo "To infinity and beyond";
    sleep 2;
done

