#!/usr/bin/env bash
#process and pid file
sudo echo "$$" > /var/run/holbertonscript.pid

trap 'echo "I hate the kill command" && exit' SIGTERM
trap "echo Y U no love me?!" SIGINT
trap "rm /var/run/holbertonscript.pid" SIGQUIT
trap "rm /var/run/holbertonscript.pid" SIGTERM
while ((1))
do
    echo "To infinity and beyond";
    sleep 2;
done
