#!/usr/bin/env bash
#print 10 times holberton school and hi in nine position
x=1
while ((x < 21))
do
if ((x==4))
then
echo "bad luck from China"
elif ((x==9))
then
echo "bad luck from Japan"
elif ((x==17))
then
echo "bad luck from Italy"
else
echo $x
fi
((x++))
done
