#!/usr/bin/env bash
file=holbertonschool

if [ -e $file ]
then
echo "holbertonschool file exists"
else
echo "holbertonschool file does not exist"
fi

if [ -s $file ]
then
echo "holbertonschool file is not empty"
else
echo "holbertonschool file is empty"
fi

if [ -d $file ]
then
:
else
echo "holbertonschool is a regular file"
fi
